---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattias-mariadb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: lvms-vg1
  volumeMode: Filesystem
